javascript-tutorial/es.javascript.info

1-js/01-getting-started/2-code-editors/article.md

- Translate to Spanish the article.md file for `Code Editors`
in the getting started sections.
- Could not translate `shareware` properly so leave it as it is.

Spanish Translation js/1-getting-started/code-editors

---

1-js/01-getting-started/1-intro/article.md

I finished the complete translation to this file.
I have added a link to the slang "syntactic sugar" for a better comprehension.

First complete translation to article.md

---

7-animation/1-bezier-curve/article.md

Animation - Bezier Cuve - Spanish Translation

 Bezier Cuve Chapter Spanish Translation

---

1-js/02-first-steps/18-javascript-specials/article.md

Este PR es la corrección al articulo traducido por el colaborador [Giorgiosaud](https://github.com/Giorgiosaud) JavaScript specials #99 . Dicho PR será cerrado y reenumerado en el Issue 17.

JavaScript specials

---

1-js/02-first-steps/10-ifelse/1-if-zero-string/solution.md
1-js/02-first-steps/10-ifelse/1-if-zero-string/task.md
1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2.svg
1-js/02-first-steps/10-ifelse/2-check-standard/ifelse_task2/index.html
1-js/02-first-steps/10-ifelse/2-check-standard/task.md
1-js/02-first-steps/10-ifelse/3-sign/if_sign/index.html
1-js/02-first-steps/10-ifelse/3-sign/solution.md
1-js/02-first-steps/10-ifelse/3-sign/task.md
1-js/02-first-steps/10-ifelse/5-rewrite-if-question/solution.md
1-js/02-first-steps/10-ifelse/5-rewrite-if-question/task.md
1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/solution.md
1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
1-js/02-first-steps/10-ifelse/article.md

Este PR es la corrección al articulo traducido por el colaborador [Giorgiosaud](https://github.com/Giorgiosaud) Conditional if #95   . Dicho PR será cerrado y reenumerado en el Issue 17.

Conditional operators: if, '?' 

---

1-js/02-first-steps/01-hello-world/1-hello-alert/index.html
1-js/02-first-steps/01-hello-world/1-hello-alert/solution.md
1-js/02-first-steps/01-hello-world/2-hello-alert-ext/alert.js
1-js/02-first-steps/01-hello-world/2-hello-alert-ext/solution.md
1-js/02-first-steps/01-hello-world/2-hello-alert-ext/task.md
1-js/02-first-steps/01-hello-world/article.md

actualización del artículo traducido por @victorze

Hello, world!

---

1-js/10-error-handling/2-custom-errors/1-format-error/solution.md
1-js/10-error-handling/2-custom-errors/1-format-error/task.md
1-js/10-error-handling/2-custom-errors/article.md

este reemplaza a #184, se cerró por falta de branch

Custom errors, extending Error

---

1-js/05-data-types/07-map-set/01-array-unique-map/task.md
1-js/05-data-types/07-map-set/02-filter-anagrams/solution.md
1-js/05-data-types/07-map-set/02-filter-anagrams/task.md
1-js/05-data-types/07-map-set/03-iterable-keys/solution.md
1-js/05-data-types/07-map-set/03-iterable-keys/task.md
1-js/05-data-types/07-map-set/article.md

Arreglado los errores de formato.

Map and Set

---

9-regular-expressions/07-regexp-escaping/article.md

Me equivoque, le agregue el titulo del capítulo anterior, este es  Escaping, special characters

Escaping, special characters

---

9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/solution.md
9-regular-expressions/09-regexp-quantifiers/1-find-text-manydots/task.md
9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/solution.md
9-regular-expressions/09-regexp-quantifiers/2-find-html-colors-6hex/task.md
9-regular-expressions/09-regexp-quantifiers/article.md

 Quantifiers +, *, ? and {n}

---

1-js/05-data-types/12-json/1-serialize-object/task.md
1-js/05-data-types/12-json/2-serialize-event-circular/solution.md
1-js/05-data-types/12-json/2-serialize-event-circular/task.md
1-js/05-data-types/12-json/article.md

actualizados los nombres de archivos

JSON methods, toJSON

---

1-js/02-first-steps/14-switch/2-rewrite-if-switch/solution.md
1-js/02-first-steps/14-switch/article.md

1-2-14 switch de rajcespedes PR 86 y 89
previamente aprobados por liz y ezze
cerradoss por conflictos y no permitir al maint modificarlos, 
article #86 x liz
solution #89 x ezze + spideep

The "switch" statement

---

2-ui/1-document/04-searching-elements-dom/1-find-elements/solution.md
2-ui/1-document/04-searching-elements-dom/1-find-elements/table.html
2-ui/1-document/04-searching-elements-dom/1-find-elements/task.md
2-ui/1-document/04-searching-elements-dom/article.md

**¡Hola!** Es mi primera contribución así que quizá haya "patinado un poco". Cualquier feedback es bien recibido y ¡espero aprender mucho para poder seguir contribuyendo!
Un saludo desde España 🦊

Searching: getElement*, querySelector* 

---

2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
2-ui/1-document/03-dom-navigation/1-dom-children/task.md
2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/task.md
2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/solution.md
2-ui/1-document/03-dom-navigation/4-select-diagonal-cells/task.md
2-ui/1-document/03-dom-navigation/article.md

Artículo, task y soluciones traducido

Walking the DOM

---

1-js/11-async/04-promise-error-handling/01-error-async/solution.md
1-js/11-async/04-promise-error-handling/01-error-async/task.md
1-js/11-async/04-promise-error-handling/article.md
1-js/11-async/04-promise-error-handling/getMessage.js

Hola, envío el PR correspondiente a la traducción de "Manejo de errores con promesas".

Error handling with promises

---

8-web-components/1-webcomponents-intro/article.md

Hay unos cuantos términos que no he traducido: Custom elements, Shadow DOM, CSS Scoping , Event retargeting .... espero al consenso : D

From the orbital height

---

1-js/11-async/05-promise-api/article.md

branch "papi" 
edito:
@vplentinax , gracias por el buen humor
parece que tengo que borrar el coment porque incomoda a potenciales revisores...

Promise API

---

4-binary/02-text-decoder/article.md

Buenas tardes, podrian revisar mi pull request de favor?
gracias
saludos,
Homero Enrique Marin Galindo

TextDecoder and TextEncoder

---

5-network/04-fetch-abort/article.md

Lo comencé hace varios días y no lo había terminado, espero que no contenga muchos errores, saludos.

Fetch: Abort

---

1-js/01-getting-started/1-intro/article.md
1-js/02-first-steps/11-logical-operators/article.md
1-js/05-data-types/04-array/article.md
1-js/05-data-types/05-array-methods/6-calculator-extendable/_js.view/solution.js
1-js/06-advanced-functions/03-closure/article.md
1-js/06-advanced-functions/05-global-object/article.md
1-js/06-advanced-functions/09-call-apply-decorators/03-debounce/task.md
1-js/06-advanced-functions/09-call-apply-decorators/04-throttle/task.md
1-js/08-prototypes/01-prototype-inheritance/article.md
1-js/09-classes/07-mixins/article.md
1-js/11-async/08-async-await/article.md
1-js/99-js-misc/04-reference-type/article.md
2-ui/1-document/11-coordinates/article.md
2-ui/2-events/02-bubbling-and-capturing/article.md
2-ui/3-event-details/4-mouse-drag-and-drop/article.md
2-ui/3-event-details/6-pointer-events/article.md
2-ui/3-event-details/8-onscroll/1-endless-page/solution.md
2-ui/3-event-details/8-onscroll/article.md
2-ui/4-forms-controls/2-focus-blur/article.md
3-frames-and-windows/01-popup-windows/article.md
5-network/01-fetch/01-fetch-users/solution.md
5-network/06-fetch-api/article.md
5-network/11-websocket/article.md
6-data-storage/01-cookie/article.md
9-regular-expressions/03-regexp-unicode/article.md

Actualización desde el 25 de Julio hasta hoy.

sync27Agosto

---

3-frames-and-windows/06-clickjacking/article.md
3-frames-and-windows/06-clickjacking/clickjacking-visible.view/facebook.html
3-frames-and-windows/06-clickjacking/clickjacking-visible.view/index.html
3-frames-and-windows/06-clickjacking/clickjacking.view/facebook.html
3-frames-and-windows/06-clickjacking/clickjacking.view/index.html
3-frames-and-windows/06-clickjacking/protector.view/iframe.html
3-frames-and-windows/06-clickjacking/top-location.view/iframe.html
3-frames-and-windows/06-clickjacking/top-location.view/index.html

The clickjacking attack

---

5-network/08-xmlhttprequest/article.md

Full translated XMLHttpRequest to spanish

XMLHttpRequest

---

2-ui/2-events/04-default-browser-action/1-why-return-false-fails/solution.md
2-ui/2-events/04-default-browser-action/1-why-return-false-fails/task.md
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.md
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/solution.view/index.html
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/source.view/index.html
2-ui/2-events/04-default-browser-action/2-catch-link-navigation/task.md
2-ui/2-events/04-default-browser-action/3-image-gallery/solution.md
2-ui/2-events/04-default-browser-action/3-image-gallery/solution.view/index.html
2-ui/2-events/04-default-browser-action/3-image-gallery/source.view/index.html
2-ui/2-events/04-default-browser-action/3-image-gallery/task.md
2-ui/2-events/04-default-browser-action/article.md
2-ui/2-events/04-default-browser-action/menu.view/menu.js

Browser default actions

---

5-network/07-url/article.md

hola! tuve algunas dudas con respecto a la traducción de algunas lineas (16, 17 por ej.), aunque intenté hacerlo de todas formas. lo siento, espero que no sea mucha molestia.
Ademas, vi algunas cosas raras en el original, como en la linea 65. Pero no estoy seguro de que sean errores o no (tampoco sabría como solucionarlo), así que decidí dejarlo como estaba.

URL objects

---

1-js/06-advanced-functions/01-recursion/01-sum-to/solution.md
1-js/06-advanced-functions/01-recursion/01-sum-to/task.md

Traducción de la tarea y solución de 1.6.1.1 sum to

Transltion of sum to task and solution

---

8-web-components/3-shadow-dom/article.md

y sombras serán
No pude traducir las herramientas de chrome porque lo tengo en inglés:
More tools > developer tools > (engranaje) > show user agent shadow dom
agregárelo quien pudiere

Shadow DOM

---

1-js/09-classes/03-static-properties-methods/3-class-extend-object/solution.md
1-js/09-classes/03-static-properties-methods/3-class-extend-object/task.md

Translate 1.9.3.3 task and solution

---

5-network/03-fetch-progress/article.md
5-network/03-fetch-progress/progress.view/index.html

Fetch: Download progress

---

8-web-components/4-template-element/article.md

Hola! Espero sus correcciones. 
Saludos!

Template element

---

1-js/01-getting-started/1-intro/article.md
1-js/02-first-steps/18-javascript-specials/article.md
1-js/04-object-basics/02-object-copy/article.md
2-ui/5-loading/02-script-async-defer/article.md
3-frames-and-windows/01-popup-windows/article.md
6-data-storage/03-indexeddb/article.md
README.md

Susy201010

---

5-network/03-fetch-progress/article.md

saltan más errorcillos cuando está online, 
y por suerte allí es fácil intercambiar idiomas para ver qué pasó.
@homero304 pasas a ser reviewer de este PR, y de paso quizas te guste empezar a hacer revisiones... 
y @vplentinax porque compartimos responsabilidad...
Lo demás, perfecto; links, code...

5.3 fetch progress.  It is not Its, it is it's instead.  =)  La frase tiene sentido como "Es un"

---

1-js/06-advanced-functions/03-closure/10-make-army/solution.md

más espacios entre lineas 40 y 122

fix format 1-6-3-10 sol

---

8-web-components/6-shadow-dom-style/article.md

Agregar documentación en español del articulo Shadow DOM styling

Shadow DOM styling

---

1-js/06-advanced-functions/01-recursion/article.md
1-js/08-prototypes/01-prototype-inheritance/article.md
1-js/11-async/01-callbacks/article.md
1-js/11-async/05-promise-api/article.md
1-js/11-async/06-promisify/article.md
1-js/11-async/08-async-await/01-rewrite-async/task.md
1-js/11-async/08-async-await/02-rewrite-async-2/task.md
1-js/11-async/08-async-await/article.md
1-js/12-generators-iterators/2-async-iterators-generators/article.md
1-js/13-modules/01-modules-intro/article.md
1-js/99-js-misc/01-proxy/01-error-nonexisting/solution.md
1-js/99-js-misc/01-proxy/01-error-nonexisting/task.md
1-js/99-js-misc/01-proxy/article.md
1-js/99-js-misc/04-reference-type/3-why-this/solution.md
1-js/99-js-misc/04-reference-type/article.md
2-ui/1-document/05-basic-dom-node-properties/article.md
2-ui/1-document/06-dom-attributes-and-properties/article.md
2-ui/5-loading/02-script-async-defer/article.md
5-network/04-fetch-abort/article.md
9-regular-expressions/16-regexp-sticky/article.md

cambios descartados y pasados a issues
1-11-6 promisify article
varios cambios, 
pero no como para rehacerlo. Sugiero ver history o blame del ingles
1-8-1 prototype inherit
solo 2 cambios muy localizados, varias lineas 
Sugiero ver history o blame del ingles
1-4-7 optional chaining
varios agregados por lo tanto num lineas trastocado  
quizas sea mejor usar diff

Susy201113

---

1-js/06-advanced-functions/10-bind/article.md

@vplentinax , cual te parece + claro?
Original:
> Function binding  
traduccion real:
> Vinculacion de funciones
Mal traducido:
> Función binding 
,( que no es nombre ni buena gramática)
Propuesto:
> Binding, vinculación de funciones  
o 
Function binding, vinculación de funciones 
( ¡ el verbo?  y traduccion) 
O creo mejor:
> Función bind, vinculacion de funciones
o 
Función bind
(BIND, que es el nombre de la funcion

Corrección de título

---

2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/solution.md
2-ui/1-document/09-size-and-scroll/1-get-scroll-height-bottom/task.md
2-ui/1-document/09-size-and-scroll/2-scrollbar-width/solution.md
2-ui/1-document/09-size-and-scroll/2-scrollbar-width/task.md
2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/task.md
2-ui/1-document/09-size-and-scroll/article.md
2-ui/1-document/09-size-and-scroll/cssWidthScroll.view/index.html

Traducción del capítulo  Element size and scrolling

Element size and scrolling

---

2-ui/3-event-details/4-mouse-drag-and-drop/1-slider/task.md
2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
2-ui/3-event-details/4-mouse-drag-and-drop/article.md

Hola @joaquinelio!
Lamento mucho la demora, tuve muchos problemas lidiando con una distro que no conocía e intenté traducir desde el celular y creé muchos problemas, así que al final, tuve que eliminar mi fork y con el el progreso, para crear un nuevo fork, un nuevo branch y bueno, aquí está el primer artículo.
PeAcE!

Drag'n'Drop with mouse events

---

1-js/05-data-types/03-string/article.md

En el ejemplo de strings inmutables se indica que el string resultante es "hola" cuando en realidad es solo "ho" debido a que se está reemplazando la variable "str" por la 'h' y por str[1] únicamente. He añadido que se incluya también str[2] y str[3] para formar la palabra completa

Corregido error en el ejemplo de strings inmutables

---

1-js/11-async/02-promise-basics/article.md

Hola! 👋
En el artículo de **'Promesa'** entre los ejemplos que se dan del uso de estas, uno de los fragmentos indica: "Si solo nos interesan las terminaciones exitosas, entonces podemos proporcionar solo un argumento de función para `.then`".
Luego el ejemplo es:
```js
let promise = new Promise(resolve => {
setTimeout(() => resolve("hecho!"), 1000);
});
promise.then(alert); // muestra "Error: ¡Vaya!" después de 1 segundo
```
Realmente ese `alert` muestra _"hecho!"_.

Devolución incorrecta de 'alert' en ejemplo

---

1-js/02-first-steps/11-logical-operators/article.md

I have corrected the **overflow of a text** that in markdown was taken as a code element, when it should be a paragraph.

Text overflow in mobile version

---

1-js/03-code-quality/03-comments/article.md

He vuelto a encontrar **texto desbordado** en la versión móvil.
Ahora lo he dejado igual que el **repositorio en inglés**:

minor fixes

---

1-js/08-prototypes/01-prototype-inheritance/article.md

In the sentence "Tenga en cuenta que proto no es lo mismo que [[Prototype]]. proto", I think it is a bit confusing to see proto after [[Prototype]], may be confused with proto as a property of [[Prototype]]

Improved readability and clarification

---

1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md

Removes a leftover English paragraph that was already translated and should have been removed.
The English sentence:
> “It’s a bit less reliable though in more complex situations...”
...was already translated above but remained in the Spanish version by mistake.
- Before:
- After:

Remove leftover English code block from translation

---

1-js/07-object-properties/01-property-descriptors/article.md
1-js/07-object-properties/02-property-accessors/article.md

The property was incorrectly referred to as `usuario.nombre` in two places.
Changed to `user.name` to reflect the actual code.
Also fixed the Markdown formatting.
- Before:
- After:

Correct variable name in comment translation

---

1-js/02-first-steps/10-ifelse/6-rewrite-if-else-question/task.md
1-js/02-first-steps/10-ifelse/article.md
1-js/02-first-steps/11-logical-operators/1-alert-null-2-undefined/solution.md
1-js/02-first-steps/11-logical-operators/2-alert-or/solution.md
1-js/02-first-steps/11-logical-operators/3-alert-1-null-2/solution.md
1-js/02-first-steps/11-logical-operators/4-alert-and/solution.md
1-js/02-first-steps/11-logical-operators/5-alert-and-or/solution.md
1-js/02-first-steps/11-logical-operators/8-if-question/solution.md
1-js/02-first-steps/11-logical-operators/9-check-login/task.md
1-js/02-first-steps/11-logical-operators/article.md

Por un error de traducción, 
se ignoraron los conceptos truthy y falsy y se los mostraba como sinonimos de tru false.
Dejo el termino inglés porque no hay traduccion adecuada  (¿"falsejo" ? ¿"verdaderito"?)
y es el que usa MDN español

Correccion de Truthy Falsy
