- CONTRIBUTING.md
- Adds references to communication channels (discord, trello)
- Refers to contributing GitHub flow
> Add CONTRIBUTING.md for spanish translation

- 1-js/02-first-steps/04-variables/1-hello-variables/solution.md
> Solucion.md

- 1-js/13-modules/02-import-export/article.md
- 1-js/13-modules/03-modules-dynamic-imports/article.md
> Sincronización 13-modules

- 1-js/07-object-properties/01-property-descriptors/article.md
- 1-js/07-object-properties/02-property-accessors/article.md
> Sincronización 07-object-properties

- 11-async/01-callbacks/article.md
> 1 11 async 1 article + task  - No tocar ni revisar ni nada

- 1-js/01-getting-started/1-intro/article.md
Hi, I have made some changes in spelling :)
> Spelling corrections

- 3-frames-and-windows/01-popup-windows/article.md
- 3-frames-and-windows/03-cross-window-communication/article.md
- 3-frames-and-windows/06-clickjacking/article.md
Sincronización directorio 3-frames-and-windows. Sin traducciones
> sync-3-frames-and-windows

- 1-js/08-prototypes/03-native-prototypes/2-defer-to-prototype-extended/solution.md
- 1-js/08-prototypes/03-native-prototypes/article.md
Updated: Corregir 1 8 3 Native prototypes (@cortizg) #291
> Native prototypes

- 1-js/01-getting-started/1-intro/article.md
- 1-js/01-getting-started/3-code-editors/article.md
- 1-js/01-getting-started/4-devtools/article.md
Habían pocas diferencias, menos mal. Pensaba que sería más duro.
> Update section AN INTRODUCTION

- 1-js/04-object-basics/09-object-toprimitive/article.md
Hi, Could you review this PR?
Thanks
Regards,
Homero Marin
> Object to primitive conversion

- 2-ui/2-events/05-dispatch-events/article.md
Hi
Could you review my PR?
Thanks
> Dispatching custom events

- 3-frames-and-windows/03-cross-window-communication/article.md
- 3-frames-and-windows/03-cross-window-communication/postmessage.view/iframe.html
- 3-frames-and-windows/03-cross-window-communication/postmessage.view/index.html
- 3-frames-and-windows/03-cross-window-communication/sandbox.view/index.html
- 3-frames-and-windows/03-cross-window-communication/sandbox.view/sandboxed.html
> Cross-window communication

- 1-js/06-advanced-functions/01-recursion/02-factorial/solution.md
- 1-js/06-advanced-functions/01-recursion/02-factorial/task.md
- 1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/solution.md
- 1-js/06-advanced-functions/01-recursion/03-fibonacci-numbers/task.md
- 1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/solution.md
- 1-js/06-advanced-functions/01-recursion/04-output-single-linked-list/task.md
- 1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/solution.md
- 1-js/06-advanced-functions/01-recursion/05-output-single-linked-list-reverse/task.md
> Add translation for all the tasks in 1.6.1

- 1-js/05-data-types/04-array/article.md
Traducción del nuevo texto en inglés.
Soluciona #404
> Translate arrays comparasion

- 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
Fixing syntax error in the solution code
> Update closure solution.md

- 1-js/04-object-basics/07-optional-chaining/article.md
https://es.javascript.info/optional-chaining
habia un err no visible de formato en ejemplo antes del resumen
> 1.4.7 opt chaining update from ENG

- 1-js/09-classes/02-class-inheritance/1-class-constructor-error/task.md
- 1-js/09-classes/02-class-inheritance/article.md
fix #408 
verificar sandboxes
https://es.javascript.info/class-inheritance
> 1 9 2 class inherit extendido y correcciones

- 1-js/06-advanced-functions/03-closure/10-make-army/solution.md
https://es.javascript.info/closure   ultimo task
Editado sobre gitlens
deberia estar identico...
sobra un svg ahora
> 1-6-3 closure 10 army solution - fix last eng update

- 8-web-components/4-template-element/article.md
Cosas que uno nota al leer con ojos de invitado:
4 fluidez, y una coma que rompe estructura  
114 Quedaba mucho mejor con la estructura cambiada, pero olvidamos cambiar la ubicacion de los dos puntos
@RocioC1207 
@vplentinax 
en lo demás se ve perfeto y biutiful
> 8 4 template, arreglos post puesta online

- 2-ui/4-forms-controls/4-forms-submit/article.md
hago pr, merge y te aviso @vplentinax  para que puedas objetar
especialmente porque cada vez veo peor.
> traducir header olvidado

- 1-js/01-getting-started/1-intro/article.md
Found a simple typo, I just added "]" to make it display as a hyperlink
> Typing error.

- 1-js/02-first-steps/10-ifelse/article.md
Error en la redacción de la pregunta del ejemplo
> Corregido error de redacción

- 5-network/02-formdata/article.md
> Misspelling

- 1-js/09-classes/01-class/article.md
Línea 69
Develemos --> Desvelemos
> Develemos --> Desvelemos

- 1-js/02-first-steps/05-types/article.md
Hola.
Me gustaría colaborar con la revisión del tutorial.
He hecho unos primeros cambios mínimos, para ver si estoy procediendo de forma adecuada, antes de meterme en más berenjenales.
Espero no haberme equivocado demasiado y que sean de ayuda.
Gracias
> Primera pruena de propuestas de cambios en la redacción.

- 1-js/05-data-types/10-destructuring-assignment/article.md
The code is missing an "="; otherwise you will get a SyntaxError.
> Minor fix in example code

- 1-js/02-first-steps/08-operators/article.md
- 1-js/02-first-steps/09-comparison/article.md
- 1-js/03-code-quality/05-testing-mocha/article.md
Fixed some typo errors that I found while reading the documentation.
> chore: fix typos

- 1-js/02-first-steps/16-function-expressions/article.md
- 1-js/05-data-types/02-number/article.md
- 1-js/08-prototypes/04-prototype-methods/article.md
- 1-js/11-async/02-promise-basics/article.md
merge desde el inglés
+
ademas del cambio ingles original 
cambie fluidez de traduccion demasiado literal y forzada a promise basic
> susy250214

- 1-js/06-advanced-functions/10-bind/5-question-use-bind/solution.md
* gramatica, 
- Falta la oposicion con "pero".
- Conjugacion.
* tecnica
- No es más complejo, es menos probable,
- Es "menos confiable", pero ante la situacion presentada ya no es "menos confiable" sino un claro error.
> Legibilidad y correccion tecnica

- 1-js/02-first-steps/03-strict-mode/article.md
si se lee bien, la 
ambigüedad es solo gramatica
pero si la quitamos queda mas facil de leer
> ambiguity issue 3853 del repo inglés
